### ISSUE TITLE
I'm getting the error Please update your Instagram app to continue..

### ISSUE THREAD

**Issue by wootwoot1234** [mislav/instagram#10]
I'm getting the following error.  Any idea how to fix it:

Please update your Instagram app to continue

**Comment by mislav** [comment]
Sorry, I can't provide support of you're using the unofficial Instagram API. Please [see the official site](https://instagram.com/developer/) for support resources.

**Comment by ydaniels** [comment]
yes thats version 4 ands that version  is long gone
