### ISSUE TITLE
Increase Video View

### ISSUE THREAD

**Issue by ferhadkonar** [mislav/instagram#11]
hi mislav, and hope you are well

I have one question,Is there a way to increase video view? I think that have private endpoint, that add view count, whit use users data such as cookie, IP ,etc.

Please help me  

Best Regard.

**Comment by mislav** [comment]
> I have one question,Is there a way to increase video view? I think that have private endpoint, that add view count, whit use users data such as cookie, IP ,etc.

No, I'm not familiar with Instagram's private API. That was a long time ago.

And also, even if you would be able to do such a thing, it would be against their Terms of Use. So best not do it!

**Comment by ferhadkonar** [comment]
thanks a lot...

**Comment by derjrjr** [comment]
github.com/mgp25/Instagram-API
