### ISSUE TITLE
no register api?

### ISSUE THREAD

**Issue by ionull** [mislav/instagram#4]
is there some problem?

**Comment by trevorprater** [comment]
AFAIK, you have to Jailbreak your device and extract the SSL certificate from the iOS app package. Once you have the cert, you can decrypt the HTTPS traffic by using something like `Charles` proxy.

**Comment by trevorprater** [comment]
I can write a tutorial if there is interest?

**Comment by mislav** [comment]
Charles can intercept HTTPS traffic if you tell it to for certain domains. See my blog post above.

However, the app may try to verify the certificate, and instead of Instagram's SSL certificate it will see Charles' own. This may be a dealbreaker, and the app may refuse to continue.

**Comment by ydaniels** [comment]
where is your blog post
